### ISSUE TITLE
Add Definition for Totality

### ISSUE THREAD

**Issue by SeverTopan** [Vulcan-Academy/Vulcanomicon#19]
As the set of all things that can be mapped to an element of the __Vulcan Set__.

**Comment by macterra** [comment]
I think Totality may be bigger than V. Proof: the Reals can be mapped onto V as a binary expansion of each real number. There is more to Totality than the Reals. Therefore there must be a many-to-one mapping of Totality onto the Vulcan set.

**Comment by macterra** [comment]
Counter-proof: everything fits in V. There are an infinite number of possible interpreters (mapped to functions or programs). You can derive Totality by applying every interpreter to every element of V. This yields V^2 but you can map V^2 back to V by interleaving the bits, therefore Totality = V.

**Comment by macterra** [comment]
Just goes to show that V has some counter-intuitive properties.

**Comment by SeverTopan** [comment]
We should maybe begin by defining our interpreters alongside Totality. We would have two sets of interpreters:
1. V -> Totality := decoder: able to map any infinite bitstring to a single subset of Totality.
2. Totality -> V := encoder: able to map any subset of totality to a single infinite bitstring.

In essence, the encoder must be able to be applied to any subset of totality, otherwise it doesn't really make sense, since different elements of V won't be consistent with one another.

Though it is true that the binary expansion of all Reals results in V, we can get around the issue by claiming that that is not a viable encoding of Reals for the purposes of Totality, since that encoding cannot be applied to _any_ subset of Totality.

**Comment by SeverTopan** [comment]
Maybe one of our future thought experiments could be coming up with what one such encoder/decoder might look like? The problem of encoding an irrational number might still be an issue.

**Comment by SeverTopan** [comment]
Computable numbers can be encoded in a finite manner via the algorithms that create them. The point of contention is then non-computables.

**Comment by SeverTopan** [comment]
Strawman: What if we redefined an Object (#22) as an Observable (#30) that has been accessed by a human? Any Object would be mappable to a _finite bitstring_ since we human observables cannot be infinite. Totality would then become the set of all Objects, which would be finite.

**Comment by macterra** [comment]
I would say an Observable is closer to a Property. An Object would then be a set of Observables. Or maybe a Model (to be defined) designed to account for a set of Observables.

**Comment by SeverTopan** [comment]
Any Objections to closing this? I think we've strayed away from this topic

**Comment by macterra** [comment]
No objections here
