### ISSUE TITLE
Add Definition for Object

### ISSUE THREAD

**Issue by SeverTopan** [Vulcan-Academy/Vulcanomicon#22]
An object being a constituent of __Totality__. Directly mappable to a __Bit String__ of infinite length in the __Vulcan Set__.

**Comment by macterra** [comment]
I would expect an object to be represented by a bit string of finite length.

Another definition: a set of related properties. I'm thinking a property is the result of a measurement or observation.

**Comment by SeverTopan** [comment]
I liked the idea that a finite bit string could be achieved by applying a filter on top of a infinite bit string (i.e. a filter that ignores all bits past index i). I'm not sure if were quite there yet in terms of our definitions though, since that relates to the concept of a pattern.

So perhaps finite objects could sit on top of infinite ones architecturally?

**Comment by SeverTopan** [comment]
This was covered in #39. Are we ok to close it?

**Comment by macterra** [comment]
No objections to closing
