### ISSUE TITLE
Develop a semantic logic example

### ISSUE THREAD

**Issue by macterra** [Vulcan-Academy/Vulcanomicon#25]

**Comment by macterra** [comment]
Let's start with something simple like "God exists"

**Comment by SeverTopan** [comment]
To take the original problem we had from #19, how could we encode all Reals with semantic logic?

**Comment by macterra** [comment]
Theoretically yes, the implications of knowing that something is a Real number are all the theorems of https://en.wikipedia.org/wiki/Real_analysis, we could just point to them.

i.e. X is a Real <-> all the theorems

**Comment by macterra** [comment]
Another possibility, much easier, what does it mean to be reasonable? i.e.

X is reasonable <->
X is rational &
X is agnostic &
X is corrigible &
X is fallible &
X is cooperative &
X is considerate
