### ISSUE TITLE
Add Definition for Actor

### ISSUE THREAD

**Issue by SeverTopan** [Vulcan-Academy/Vulcanomicon#40]
An Actor is the base class of an Agent. It can perform actions, but does not exhibit philosophical agency. E.g. A thermostat can be defined as an Actor. This should resolve the agency ambiguity in #28.

**Comment by SeverTopan** [comment]
A System would then be categorized as an Actor, or an Agent based on the (Kolmogorov?) complexity of the function correlating its __Decision__ (#43).

**Comment by SeverTopan** [comment]
There would then be a gradient between __Actor__ and __Agent__, with the delineation drawn arbitrarily.

**Comment by macterra** [comment]
Maybe an Agent is an Actor that uses a World Model?

**Comment by macterra** [comment]
I would think Actors are Systems rather than the other way around but I'm willing to be convinced...

**Comment by SeverTopan** [comment]
I agree that Actors are Systems, I think my comment was a little ambiguous. What I was trying to say is that the assessment of whether something is an Agent or an Actor relies on the Agent or Actor's Decision complexity.

**Comment by SeverTopan** [comment]
Re: https://github.com/Vulcan-Academy/Vulcan-Academy.github.io/issues/40#issuecomment-373399012, I'd argue the presence of a World Model factors into Decision complexity.

**Comment by macterra** [comment]
I agree the World Model factors into Decision complexity, but I would say that distinguishes simple agents from complex agents rather than actors from agents. To test this design how would you classify gravity?

**Comment by SeverTopan** [comment]
What if i have a very simple world model? Conversely, we can imagine a very complex Decision that does not utilize a World Model at all. 

My interpretation is that a World Model is just a strategy with which we can increase the complexity of a Decision, but its not strictly needed for a complex agent. The World Model is in a way anthropocentric.

Gravity could be defined as an Action of the "Physics" Actor. There are multiple ways to represent it but I think it sits at the low Decision Complexity end of the spectrum.
