### ISSUE TITLE
Add Definition for Model

### ISSUE THREAD

**Issue by SeverTopan** [Vulcan-Academy/Vulcanomicon#45]
A __System__ that represents another __System__, as per https://github.com/Vulcan-Academy/Vulcan-Academy.github.io/issues/41#issuecomment-373401043.

**Comment by macterra** [comment]
What counts as a model? Obviously maps, recordings (audio, visual, etc). Also mental models (beliefs and values, propositions and claims). Models are special in that only models can be assigned a truth value, indicating to what extent the model accurately represents its subject.

**Comment by macterra** [comment]
Also simulations and scientific models which would include mathematical models.
